main: me.metamechanists.MMQ
name: MMQ
version: 0.2
description: A small custom plugin for handling quests
api-version: 1.17
author: Idra
depend: [Slimefun, LuckPerms]

commands:
  quest:
    permission: mmq.quest
    description: "Open the quest GUI"
  itemstacksave:
    permission: mmq.itemstacksave
    description: "Save an itemstack to itemstacks.yml"

permissions:
  mmq.quest:
    description: "Allows the usage of /quest"
    default: true
  mmq.itemstacksave:
    description: "Allows the usage of /itemstacksave"
    default: op
  mmq.questreload:
    description: "Reloads the config files for MMQ"
    default: op